# Welcome to Ultimate Jekyll!
# This is the default configuration file for your project.

# Project
url: "https://ultimate-jekyll.itwcreativeworks.com"
baseurl: ""

# Theme
theme:
  id: "classy"
  target: "frontend"
  appearance: "dark"
  version: "latest"
  html:
    class: ""
  body:
    class: ""
  nav:
    enabled: true
  main:
    class: ""
  footer:
    enabled: true

# Meta
meta:
  title: "Ultimate Jekyll - An all-in-one Jekyll framework for modern websites."
  description: "Ultimate Jekyll is a powerful, flexible, and easy-to-use Jekyll theme for building modern websites. Complete with pre-built sections, dark mode, and more."
  image: "https://cdn.itwcreativeworks.com/assets/itw-creative-works/images/socials/itw-creative-works-brandmark-square-black-1024x1024.png"
  keywords: ""
  viewport: ""
  index: true
  referrer: ""

# Brand
brand:
  id: "ultimate-jekyll"
  name: "Ultimate Jekyll"
  description: "Ultimate Jekyll is a powerful, flexible, and easy-to-use Jekyll theme for building modern websites."
  type: "Corporation"
  images:
    brandmark: "https://cdn.itwcreativeworks.com/assets/itw-creative-works/images/logo/itw-creative-works-brandmark-black-x.svg"
    wordmark: "https://cdn.itwcreativeworks.com/assets/itw-creative-works/images/logo/itw-creative-works-wordmark-black-x.svg"
    combomark: "https://cdn.itwcreativeworks.com/assets/itw-creative-works/images/logo/itw-creative-works-combomark-black-x.svg"
  contact:
    email: ""
    phone: ""
    slapform-form-id: ""
  address:
    line1: "4001 Inglewood Ave"
    line2: "Suite 101-385"
    region: "CA"
    postal-code: "90278"
    city: "Redondo Beach"
    locality: "Los Angeles"
    country: "United States"

# Web Manager
web_manager:
  auth:
    enabled: true
    config:
      policy: null
      redirects:
        authenticated: "/account"
        unauthenticated: "/signup"
      allowSubdomains: true
  firebase:
    app:
      enabled: true
      config:
        apiKey: "AIzaSyDzy5BG9-i9RmymyFx6mfwSgaRioyfa0Cc"
        authDomain: "ultimate-jekyll.itwcreativeworks.com"
        databaseURL: "https://ultimate-jekyll.firebaseio.com"
        projectId: "ultimate-jekyll"
        storageBucket: "ultimate-jekyll.appspot.com"
        messagingSenderId: "837186164890"
        appId: "1:837186164890:web:f1f59569d661078c"
        measurementId: "G-FR3X7X4KYN"
    appCheck:
      enabled: false
      config:
        siteKey: "6LeVGTsoAAAAADvAyVkTLYXq5dP36GaBryN2s87H"
  cookieConsent:
    enabled: true
    config:
      palette:
        popup:
          background: "#237afc"
          text: "#fff"
        button:
          background: "#fff"
          text: "#237afc"
  chatsy:
    enabled: true
    config:
      accountId: "pLnXvh03xRQOHWAurn5EBnobC5H3"
      chatId: "t4IJJsOMNc4hiH"
      settings:
        openChatButton:
          background: "#237afc"
          text: "#fff"
  sentry:
    enabled: true
    config:
      dsn: ""
      release: "ultimate-jekyll-website"
      replaysSessionSampleRate: 0.01
      replaysOnErrorSampleRate: 0.01
  exitPopup:
    enabled: true
    config:
      timeout: 1000 * 60 * 60 * 4
      title: "Want 15% off?"
      message: "Get 15% off your purchase of our Premium plans."
      okButton:
        text: "Claim 15% Discount"
        link: "/pricing"
  lazyLoading:
    enabled: true
    config:
      rootMargin: "50px 0px"
      threshold: 0.01
  socialSharing:
    enabled: false
    config:
      defaultPlatforms: ["facebook", "twitter", "linkedin", "pinterest", "reddit", "email", "copy"]
      buttonClass: ""
      openInNewWindow: true
  pushNotifications:
    enabled: true
    config:
      autoRequest: 1000 * 60
  validRedirectHosts: []

# Socials
socials:
  facebook: null
  twitter: null
  linkedin: null
  youtube: null
  instagram: null
  tumblr: null
  slack: null
  discord: null
  github: null
  dev: null
  tiktok: null
  twitch: null
  soundcloud: null
  spotify: null
  mixcloud: null

# Tracking
tracking:
  google-analytics: null
  meta-pixel: null
  tiktok-pixel: null

# Favicon
favicon:
  path: "https://cdn.itwcreativeworks.com/assets/itw-creative-works/images/favicon"
  safari-pinned-tab: "#5bbad5"
  msapp-tile-color: "#da532c"
  theme-color: "#ffffff"

# Cloudflare
cloudflare:
  zone: null

# Download
download:
  mac:
    universal: ""
  windows:
    universal: ""
  linux:
    debian: ""
    snap: ""
  ios:
    universal: ""
  android:
    universal: ""

# Extension
extension:
  chrome: ""
  firefox: ""
  opera: ""
  safari: ""
  edge: ""

# Manifest
manifest:
  name: ""
  short-name: ""
  theme-color: "#ffffff"
  background-color: "#ffffff"
  display: "standalone"
  start-url: "/?source=pwa"
  scope: "/"
  orientation: "portrait"

# Translation
translation:
  enabled: false
  default: "en"
  languages:
    - "zh"
    - "es"
    - "hi"
    - "ar"
    - "pt"
    - "ru"
    - "ja"
    - "de"
    - "fr"
    - "ko"
    - "ur"
    - "id"
    - "bn"
    - "tl"
    - "vi"
    - "it"

# Icons
icons:
  style: "solid"

# Blog & Pagination
permalink: /blog/:title
pagination:
  enabled: true
  per_page: 6
  offset: 0
  limit: 0
  permalink: /page/:num.html
  title: :title - page :num
  sort_field: date
  sort_reverse: true

# Jekyll collections
collections:
  team:
    title: Team Members
    output: true

# Jekyll defaults
defaults:
- scope:
    path: ""
    type: team
  values:
    permalink: /team/:title
